-- MySQL Script generated by MySQL Workbench
-- Mon Dec 18 19:41:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`menu` (
  `ID` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `description` VARCHAR(350) NULL,
  `weight` SMALLINT UNSIGNED NOT NULL,
  `price` DECIMAL(7,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`deliveryman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`deliveryman` (
  `ID` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(75) NULL,
  `phonenumber` VARCHAR(20) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`deliveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`deliveries` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `deliveryID` VARCHAR(4) NOT NULL,
  `menuID` SMALLINT UNSIGNED NOT NULL,
  `quantity` TINYINT UNSIGNED NOT NULL,
  `customerName` VARCHAR(75) NULL,
  `telephone` VARCHAR(20) NULL,
  `address` VARCHAR(200) NULL,
  `orderDate` TIMESTAMP NOT NULL,
  `deliverymanID` SMALLINT UNSIGNED NOT NULL,
  `deliveryDate` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `menuID_idx` (`menuID` ASC) VISIBLE,
  INDEX `deliverymanID_idx` (`deliverymanID` ASC) VISIBLE,
  CONSTRAINT `menuID`
    FOREIGN KEY (`menuID`)
    REFERENCES `pizzeria`.`menu` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `deliverymanID`
    FOREIGN KEY (`deliverymanID`)
    REFERENCES `pizzeria`.`deliveryman` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
